// Display (en), Display (html), 2char Google Translate
var languagesAll =
[["Afrikaans", "Afrikaans", "af"],
 ["Albanian", "Shqip", "sq"],
 ["Arabic", "عربي", "ar"],
 ["Armenian", "Հայերէն", "hy"],
 ["Azerbaijani", "آذربایجان دیلی", "az"],
 ["Basque", "Euskara", "eu"],
 ["Belarusian", "Беларуская", "be"],
 ["Bulgarian", "Български", "bg"],
 ["Catalan", "Català", "ca"],
 ["Chinese (Simplified)", "中文简体", "zh-CN"],
 ["Chinese (Traditional)", "中文繁體", "zh-TW"],
 ["Croatian", "Hrvatski", "hr"],
 ["Czech", "Čeština", "cs"],
 ["Danish", "Dansk", "da"],
 ["Dutch", "Nederlands", "nl"],
 ["English", "English", "en"],
 ["Estonian", "Eesti keel", "et"],
 ["Filipino", "Filipino", "tl"],
 ["Finnish", "Suomi", "fi"],
 ["French", "Français", "fr"],
 ["Galician", "Galego", "gl"],
 ["Georgian", "ქართული", "ka"],
 ["German", "Deutsch", "de"],
 ["Greek", "Ελληνικά", "el"],
 ["Haitian Creole", "Kreyòl ayisyen", "ht"],
 ["Hebrew", "עברית", "iw"],
 ["Hindi", "हिन्दी", "hi"],
 ["Hungarian", "Magyar", "hu"],
 ["Icelandic", "Íslenska", "is"],
 ["Indonesian", "Bahasa Indonesia", "id"],
 ["Irish", "Gaeilge", "ga"],
 ["Italian", "Italiano", "it"],
 ["Japanese", "日本語", "ja"],
 ["Korean", "한국어", "ko"],
 ["Latvian", "Latviešu", "lv"],
 ["Lithuanian", "Lietuvių kalba", "lt"],
 ["Macedonian", "Македонски", "mk"],
 ["Malay", "Malay", "ms"],
 ["Maltese", "Malti", "mt"],
 ["Norwegian", "Norsk", "no"],
 ["Persian", "فارسی", "fa"],
 ["Polish", "Polski", "pl"],
 ["Portuguese", "Português", "pt"],
 ["Romanian", "Română", "ro"],
 ["Russian", "Русский", "ru"],
 ["Serbian", "Српски", "sr"],
 ["Slovak", "Slovenčina", "sk"],
 ["Slovenian", "Slovensko", "sl"],
 ["Spanish", "Español", "es"],
 ["Swahili", "Kiswahili", "sw"],
 ["Swedish", "Svenska", "sv"],
 ["Thai", "ไทย", "th"],
 ["Turkish", "Türkçe", "tr"],
 ["Ukrainian", "Українська", "uk"],
 ["Urdu", "اردو", "ur"],
 ["Vietnamese", "Tiếng Việt", "vi"],
 ["Welsh", "Cymraeg", "cy"],
 ["Yiddish", "ייִדיש", "yi"]
]